--회원 테이블
CREATE TABLE SPR_USER
(
    USER_ID VARCHAR2(100) NOT NULL,
    USER_PWD VARCHAR2(20),
    USER_NAME VARCHAR2(30),
    USER_EMAIL VARCHAR2(50),
    STATUS CHAR(1),
    REG_DATE DATE,
    ADDR_CODE CHAR(5),
    ADDR_BASE VARCHAR2(200),
    ADDR_DETAIL VARCHAR2(200),
    RATING CHAR(1)
);

COMMENT ON TABLE SPR_USER IS '회원 테이블';
COMMENT ON COLUMN SPR_USER.USER_ID IS '아이디';
COMMENT ON COLUMN SPR_USER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN SPR_USER.USER_NAME IS '이름';
COMMENT ON COLUMN SPR_USER.USER_EMAIL IS '이메일';
COMMENT ON COLUMN SPR_USER.STATUS IS '상태(Y:정상 N:정지)';
COMMENT ON COLUMN SPR_USER.REG_DATE IS '가입일';
COMMENT ON COLUMN SPR_USER.ADDR_CODE IS '우편번호';
COMMENT ON COLUMN SPR_USER.ADDR_BASE IS '주소';
COMMENT ON COLUMN SPR_USER.ADDR_DETAIL IS '상세주소';
COMMENT ON COLUMN SPR_USER.RATING IS '등급';

ALTER TABLE SPR_USER
ADD CONSTRAINT SPR_USER PRIMARY KEY(USER_ID);

--전시 게시판
CREATE TABLE SPR_EXHIBITION
(
    BRD_SEQ NUMBER(12) NOT NULL,
    USER_ID VARCHAR2(100),
    BRD_GROUP NUMBER(12),
    BRD_ORDER NUMBER(10),
    BRD_INDENT NUMBER(10),
    BRD_TITLE VARCHAR2(150),
    BRD_CONTENT CLOB,
    BRD_READ_CNT NUMBER(10),
    REG_DATE DATE,
    BRD_PARENT NUMBER(12),
    MOD_DATE DATE,
    START_DATE DATE,
    END_DATE DATE
);

COMMENT ON TABLE SPR_EXHIBITION IS '전시 게시판';
COMMENT ON COLUMN SPR_EXHIBITION.BRD_SEQ IS '게시물 번호';
COMMENT ON COLUMN SPR_EXHIBITION.USER_ID IS '아이디';
COMMENT ON COLUMN SPR_EXHIBITION.BRD_GROUP IS '그룹번호';
COMMENT ON COLUMN SPR_EXHIBITION.BRD_ORDER IS '그룹순서';
COMMENT ON COLUMN SPR_EXHIBITION.BRD_INDENT IS '들여쓰기';
COMMENT ON COLUMN SPR_EXHIBITION.BRD_TITLE IS '게시물 제목';
COMMENT ON COLUMN SPR_EXHIBITION.BRD_CONTENT IS '게시물 내용';
COMMENT ON COLUMN SPR_EXHIBITION.BRD_READ_CNT IS '게시물 조회수';
COMMENT ON COLUMN SPR_EXHIBITION.REG_DATE IS '게시물 등록일';
COMMENT ON COLUMN SPR_EXHIBITION.BRD_PARENT IS '부모게시물 번호';
COMMENT ON COLUMN SPR_EXHIBITION.MOD_DATE IS '수정일';
COMMENT ON COLUMN SPR_EXHIBITION.START_DATE IS '전시 시작일';
COMMENT ON COLUMN SPR_EXHIBITION.END_DATE IS '전시 마감일';

--전시 게시판 SPR_EXHIBITION 시퀀스
CREATE SEQUENCE SEQ_EXHIBITION_SEQ
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999
NOCACHE;

CREATE UNIQUE INDEX XPK_SPR_EXHIBITION ON SPR_EXHIBITION(BRD_SEQ ASC);

ALTER TABLE SPR_EXHIBITION
ADD CONSTRAINT SPR_EXHIBITION PRIMARY KEY(BRD_SEQ);

--FK
ALTER TABLE SPR_EXHIBITION
ADD CONSTRAiNT FK_SPR_EXHIBITION_USERID FOREIGN KEY(USER_ID)
REFERENCES SPR_USER(USER_ID);

--전시 게시판 첨부파일
CREATE TABLE EXHIBITION_FILE
(
    FILE_SEQ NUMBER(3,0) NOT NULL,
    FILE_ORG_NAME VARCHAR2(100),
    FILE_NAME VARCHAR2(50),
    FILE_EXT VARCHAR2(20),
    FILE_SIZE NUMBER(12,0),
    REG_DATE DATE,
    BRD_SEQ NUMBER(12)
);

COMMENT ON TABLE EXHIBITION_FILE IS '전시 게시판 첨부파일';
COMMENT ON COLUMN EXHIBITION_FILE.FILE_SEQ IS '파일번호';
COMMENT ON COLUMN EXHIBITION_FILE.FILE_ORG_NAME IS '원본파일명';
COMMENT ON COLUMN EXHIBITION_FILE.FILE_NAME IS '서버파일명';
COMMENT ON COLUMN EXHIBITION_FILE.FILE_EXT IS '파일확장자';
COMMENT ON COLUMN EXHIBITION_FILE.FILE_SIZE IS '파일크기';
COMMENT ON COLUMN EXHIBITION_FILE.REG_DATE IS '등록날짜';
COMMENT ON COLUMN EXHIBITION_FILE.BRD_SEQ IS '게시물번호';

CREATE UNIQUE INDEX XPK_EXHIBITION_FILE ON EXHIBITION_FILE(FILE_SEQ ASC, BRD_SEQ ASC);

ALTER TABLE EXHIBITION_FILE
ADD CONSTRAINT XPK_EXHIBITION_FILE PRIMARY KEY(FILE_SEQ, BRD_SEQ);

ALTER TABLE EXHIBITION_FILE
ADD CONSTRAINT FK_EXHIBITION_FILE FOREIGN KEY(BRD_SEQ)
REFERENCES SPR_EXHIBITION(BRD_SEQ);

--문의사항 게시판
CREATE TABLE SPR_QNA
(
    BRD_SEQ NUMBER(12) NOT NULL,
    USER_ID VARCHAR2(100),
    BRD_GROUP NUMBER(12),
    BRD_ORDER NUMBER(10),
    BRD_INDENT NUMBER(10),
    BRD_TITLE VARCHAR2(150),
    BRD_CONTENT CLOB,
    BRD_READ_CNT NUMBER(10),
    REG_DATE DATE,
    BRD_PARENT NUMBER(12),
    MOD_DATE DATE
);

COMMENT ON TABLE SPR_QNA IS '문의사항 게시판';
COMMENT ON COLUMN SPR_QNA.BRD_SEQ IS '게시물 번호';
COMMENT ON COLUMN SPR_QNA.USER_ID IS '아이디';
COMMENT ON COLUMN SPR_QNA.BRD_GROUP IS '그룹번호';
COMMENT ON COLUMN SPR_QNA.BRD_ORDER IS '그룹순서';
COMMENT ON COLUMN SPR_QNA.BRD_INDENT IS '들여쓰기';
COMMENT ON COLUMN SPR_QNA.BRD_TITLE IS '게시물 제목';
COMMENT ON COLUMN SPR_QNA.BRD_CONTENT IS '게시물 내용';
COMMENT ON COLUMN SPR_QNA.BRD_READ_CNT IS '게시물 조회수';
COMMENT ON COLUMN SPR_QNA.REG_DATE IS '게시물 등록일';
COMMENT ON COLUMN SPR_QNA.BRD_PARENT IS '부모게시물 번호';
COMMENT ON COLUMN SPR_QNA.MOD_DATE IS '수정일';

--문의사항 게시판 SPR_QNA 시퀀스
CREATE SEQUENCE SEQ_QNA_SEQ
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999
NOCACHE;

CREATE UNIQUE INDEX XPK_SPR_QNA ON SPR_QNA(BRD_SEQ ASC);

ALTER TABLE SPR_QNA
ADD CONSTRAINT SPR_QNA PRIMARY KEY(BRD_SEQ);

--FK
ALTER TABLE SPR_QNA
ADD CONSTRAiNT FK_SPR_QNA_USERID FOREIGN KEY(USER_ID)
REFERENCES SPR_USER(USER_ID);

--문의사항 게시판 첨부파일
CREATE TABLE QNA_FILE
(
    FILE_SEQ NUMBER(3,0) NOT NULL,
    FILE_ORG_NAME VARCHAR2(100),
    FILE_NAME VARCHAR2(50),
    FILE_EXT VARCHAR2(20),
    FILE_SIZE NUMBER(12,0),
    REG_DATE DATE,
    BRD_SEQ NUMBER(12)
);

COMMENT ON TABLE QNA_FILE IS '문의사항 게시판 첨부파일';
COMMENT ON COLUMN QNA_FILE.FILE_SEQ IS '파일번호';
COMMENT ON COLUMN QNA_FILE.FILE_ORG_NAME IS '원본파일명';
COMMENT ON COLUMN QNA_FILE.FILE_NAME IS '서버파일명';
COMMENT ON COLUMN QNA_FILE.FILE_EXT IS '파일확장자';
COMMENT ON COLUMN QNA_FILE.FILE_SIZE IS '파일크기';
COMMENT ON COLUMN QNA_FILE.REG_DATE IS '등록날짜';
COMMENT ON COLUMN QNA_FILE.BRD_SEQ IS '게시물번호';

CREATE UNIQUE INDEX XPK_QNA_FILE ON QNA_FILE(FILE_SEQ ASC, BRD_SEQ ASC);

ALTER TABLE QNA_FILE
ADD CONSTRAINT XPK_QNA_FILE PRIMARY KEY(FILE_SEQ, BRD_SEQ);

ALTER TABLE QNA_FILE
ADD CONSTRAINT FK_QNA_FILE FOREIGN KEY(BRD_SEQ)
REFERENCES SPR_QNA(BRD_SEQ);

--자유 게시판
CREATE TABLE SPR_FREE
(
    BRD_SEQ NUMBER(12) NOT NULL,
    USER_ID VARCHAR2(100),
    BRD_GROUP NUMBER(12),
    BRD_ORDER NUMBER(10),
    BRD_INDENT NUMBER(10),
    BRD_TITLE VARCHAR2(150),
    BRD_CONTENT CLOB,
    BRD_READ_CNT NUMBER(10),
    REG_DATE DATE,
    BRD_PARENT NUMBER(12),
    MOD_DATE DATE
);

COMMENT ON TABLE SPR_FREE IS '자유 게시판';
COMMENT ON COLUMN SPR_FREE.BRD_SEQ IS '게시물 번호';
COMMENT ON COLUMN SPR_FREE.USER_ID IS '아이디';
COMMENT ON COLUMN SPR_FREE.BRD_GROUP IS '그룹번호';
COMMENT ON COLUMN SPR_FREE.BRD_ORDER IS '그룹순서';
COMMENT ON COLUMN SPR_FREE.BRD_INDENT IS '들여쓰기';
COMMENT ON COLUMN SPR_FREE.BRD_TITLE IS '게시물 제목';
COMMENT ON COLUMN SPR_FREE.BRD_CONTENT IS '게시물 내용';
COMMENT ON COLUMN SPR_FREE.BRD_READ_CNT IS '게시물 조회수';
COMMENT ON COLUMN SPR_FREE.REG_DATE IS '게시물 등록일';
COMMENT ON COLUMN SPR_FREE.BRD_PARENT IS '부모게시물 번호';
COMMENT ON COLUMN SPR_FREE.MOD_DATE IS '수정일';

--자유 게시판 SPR_FREE 시퀀스
CREATE SEQUENCE SEQ_FREE_SEQ
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999
NOCACHE;

CREATE UNIQUE INDEX XPK_SPR_FREE ON SPR_FREE(BRD_SEQ ASC);

ALTER TABLE SPR_FREE
ADD CONSTRAINT SPR_FREE PRIMARY KEY(BRD_SEQ);

--FK
ALTER TABLE SPR_FREE
ADD CONSTRAiNT FK_SPR_FREE_USERID FOREIGN KEY(USER_ID)
REFERENCES SPR_USER(USER_ID);

--문의사항 게시판 첨부파일
CREATE TABLE FREE_FILE
(
    FILE_SEQ NUMBER(3,0) NOT NULL,
    FILE_ORG_NAME VARCHAR2(100),
    FILE_NAME VARCHAR2(50),
    FILE_EXT VARCHAR2(20),
    FILE_SIZE NUMBER(12,0),
    REG_DATE DATE,
    BRD_SEQ NUMBER(12)
);

COMMENT ON TABLE FREE_FILE IS '자유사항 게시판 첨부파일';
COMMENT ON COLUMN FREE_FILE.FILE_SEQ IS '파일번호';
COMMENT ON COLUMN FREE_FILE.FILE_ORG_NAME IS '원본파일명';
COMMENT ON COLUMN FREE_FILE.FILE_NAME IS '서버파일명';
COMMENT ON COLUMN FREE_FILE.FILE_EXT IS '파일확장자';
COMMENT ON COLUMN FREE_FILE.FILE_SIZE IS '파일크기';
COMMENT ON COLUMN FREE_FILE.REG_DATE IS '등록날짜';
COMMENT ON COLUMN FREE_FILE.BRD_SEQ IS '게시물번호';

CREATE UNIQUE INDEX XPK_FREE_FILE ON FREE_FILE(FILE_SEQ ASC, BRD_SEQ ASC);

ALTER TABLE FREE_FILE
ADD CONSTRAINT XPK_FREE_FILE PRIMARY KEY(FILE_SEQ, BRD_SEQ);

ALTER TABLE FREE_FILE
ADD CONSTRAINT FK_FREE_FILE FOREIGN KEY(BRD_SEQ)
REFERENCES SPR_FREE(BRD_SEQ);

--공지사항 게시판
CREATE TABLE SPR_NOTICE
(
    BRD_SEQ NUMBER(12) NOT NULL,
    USER_ID VARCHAR2(100),
    BRD_GROUP NUMBER(12),
    BRD_ORDER NUMBER(10),
    BRD_INDENT NUMBER(10),
    BRD_TITLE VARCHAR2(150),
    BRD_CONTENT CLOB,
    BRD_READ_CNT NUMBER(10),
    REG_DATE DATE,
    BRD_PARENT NUMBER(12),
    MOD_DATE DATE
);

COMMENT ON TABLE SPR_NOTICE IS '공지사항 게시판';
COMMENT ON COLUMN SPR_NOTICE.BRD_SEQ IS '게시물 번호';
COMMENT ON COLUMN SPR_NOTICE.USER_ID IS '아이디';
COMMENT ON COLUMN SPR_NOTICE.BRD_GROUP IS '그룹번호';
COMMENT ON COLUMN SPR_NOTICE.BRD_ORDER IS '그룹순서';
COMMENT ON COLUMN SPR_NOTICE.BRD_INDENT IS '들여쓰기';
COMMENT ON COLUMN SPR_NOTICE.BRD_TITLE IS '게시물 제목';
COMMENT ON COLUMN SPR_NOTICE.BRD_CONTENT IS '게시물 내용';
COMMENT ON COLUMN SPR_NOTICE.BRD_READ_CNT IS '게시물 조회수';
COMMENT ON COLUMN SPR_NOTICE.REG_DATE IS '게시물 등록일';
COMMENT ON COLUMN SPR_NOTICE.BRD_PARENT IS '부모게시물 번호';
COMMENT ON COLUMN SPR_NOTICE.MOD_DATE IS '수정일';

--공지사항 게시판 SPR_NOTICE 시퀀스
CREATE SEQUENCE SEQ_NOTICE_SEQ
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999
NOCACHE;

CREATE UNIQUE INDEX XPK_SPR_NOTICE ON SPR_NOTICE(BRD_SEQ ASC);

ALTER TABLE SPR_NOTICE
ADD CONSTRAINT SPR_NOTICE PRIMARY KEY(BRD_SEQ);

--FK
ALTER TABLE SPR_NOTICE
ADD CONSTRAiNT FK_SPR_NOTICE_USERID FOREIGN KEY(USER_ID)
REFERENCES SPR_USER(USER_ID);

--문의사항 게시판 첨부파일
CREATE TABLE NOTICE_FILE
(
    FILE_SEQ NUMBER(3,0) NOT NULL,
    FILE_ORG_NAME VARCHAR2(100),
    FILE_NAME VARCHAR2(50),
    FILE_EXT VARCHAR2(20),
    FILE_SIZE NUMBER(12,0),
    REG_DATE DATE,
    BRD_SEQ NUMBER(12)
);

COMMENT ON TABLE NOTICE_FILE IS '문의사항 게시판 첨부파일';
COMMENT ON COLUMN NOTICE_FILE.FILE_SEQ IS '파일번호';
COMMENT ON COLUMN NOTICE_FILE.FILE_ORG_NAME IS '원본파일명';
COMMENT ON COLUMN NOTICE_FILE.FILE_NAME IS '서버파일명';
COMMENT ON COLUMN NOTICE_FILE.FILE_EXT IS '파일확장자';
COMMENT ON COLUMN NOTICE_FILE.FILE_SIZE IS '파일크기';
COMMENT ON COLUMN NOTICE_FILE.REG_DATE IS '등록날짜';
COMMENT ON COLUMN NOTICE_FILE.BRD_SEQ IS '게시물번호';

CREATE UNIQUE INDEX XPK_NOTICE_FILE ON NOTICE_FILE(FILE_SEQ ASC, BRD_SEQ ASC);

ALTER TABLE NOTICE_FILE
ADD CONSTRAINT XPK_NOTICE_FILE PRIMARY KEY(FILE_SEQ, BRD_SEQ);

ALTER TABLE NOTICE_FILE
ADD CONSTRAINT FK_NOTICE_FILE FOREIGN KEY(BRD_SEQ)
REFERENCES SPR_NOTICE(BRD_SEQ);

-------------XML--------------------------
SELECT  	USER_ID,
            NVL(USER_PWD, '') USER_PWD,
            NVL(USER_NAME, '') USER_NAME,
            NVL(USER_EMAIL, '') USER_EMAIL,
            NVL(STATUS, '') STATUS,
            NVL(TO_CHAR(REG_DATE, 'YYYY.MM.DD HH24:MI:SS'), '') REG_DATE,
            NVL(ADDR_CODE, '') ADDR_CODE,
            NVL(ADDR_BASE, '') ADDR_BASE,
            NVL(ADDR_DETAIL, '') ADDR_DETAIL,
            NVL(RATING, '') RATING
  FROM  	SPR_USER
 WHERE 	USER_ID = 'test';
 
INSERT INTO SPR_USER (
    USER_ID,
    USER_PWD,
    USER_NAME,
    USER_EMAIL,
    STATUS,
    REG_DATE,
    ADDR_CODE,
    ADDR_BASE,
    ADDR_DETAIL,
    RATING
) VALUES (
    :V0,
    :V1,
    :V2,
    :V3,
    :V4,
    SYSDATE,
    :V6,
    :V7,
    :V8,
    :V9
);

UPDATE  SPR_USER
   SET  A = B
        USER_PWD = :V1
        USER_NAME = :V2
        USER_EMAIL = :V3
        STATUS = :V4
        REG_DATE = :V5
        ADDR_CODE = :V6
        ADDR_BASE = :V7
        ADDR_DETAIL = :V8
        RATING = :V9
  WHERE USER_ID = :V0;

UPDATE SPR_USER
SET USER_PWD = '1111'
WHERE USER_ID = 'test'
  AND USER_EMAIL = '1234';

ROLLBACK;

UPDATE SPR_USER
SET STATUS = 'N'
WHERE USER_ID = 'adeodato';

ALTER TABLE SPR_USER
ADD FAKE_PWD_STATUS CHAR(1 BYTE) DEFAULT 'Y';

COMMENT ON COLUMN SPR_USER.FAKE_PWD_STATUS IS '상태(Y:정상비밀번호 N:임시비밀번호)';

ALTER TABLE SPR_USER
DROP COLUMN FAKE_PWD_STATUS;

UPDATE SPR_USER
   SET FAKE_PWD_STATUS = 'N'
 WHERE USER_ID = 'test1';
 
 UPDATE SPR_USER SET FAKE_PWD_STATUS = 'Y' WHERE USER_ID = 'test1';
 
SELECT SEQ_NOTICE_SEQ.NEXTVAL FROM DUAL;
SELECT SEQ_FREE_SEQ.NEXTVAL FROM DUAL;
SELECT SEQ_EXHIBITION_SEQ.NEXTVAL FROM DUAL;
SELECT SEQ_QNA_SEQ.NEXTVAL FROM DUAL;

SELECT BRD_SEQ,
               USER_ID,
               USER_NAME,
               USER_EMAIL,
               BRD_GROUP,
               BRD_ORDER,
               BRD_INDENT,
               BRD_TITLE,
               BRD_CONTENT,
               BRD_READ_CNT,
               REG_DATE, 
               BRD_PARENT,
               MOD_DATE
        FROM (SELECT ROWNUM AS RNUM,
                     BRD_SEQ,
                     USER_ID,
                     USER_NAME,
                     USER_EMAIL,
                     BRD_GROUP,
                     BRD_ORDER,
                     BRD_INDENT,
                     BRD_TITLE,
                     BRD_CONTENT,
                     BRD_READ_CNT,
                     REG_DATE, 
                     BRD_PARENT,
                     MOD_DATE
              FROM (SELECT A.BRD_SEQ AS BRD_SEQ,
                           A.USER_ID,
                           NVL(B.USER_NAME, '') AS USER_NAME,
                           NVL(B.USER_EMAIL, '') AS USER_EMAIL,
                           NVL(A.BRD_GROUP, 0) AS BRD_GROUP,
                           NVL(A.BRD_ORDER, 0) AS BRD_ORDER,
                           NVL(A.BRD_INDENT, 0) AS BRD_INDENT,
                           NVL(A.BRD_TITLE, '') AS BRD_TITLE,
                           NVL(A.BRD_CONTENT, '') AS BRD_CONTENT,
                           NVL(A.BRD_READ_CNT, 0) AS BRD_READ_CNT,
                           NVL(TO_CHAR(A.REG_DATE, 'YYYY.MM.DD HH24:MI:SS'), '') AS REG_DATE, 
                           NVL(A.BRD_PARENT, 0) AS BRD_PARENT,
                           NVL(MOD_DATE, '') AS MOD_DATE
FROM SPR_QNA A, SPR_USER B
 WHERE A.USER_ID = B.USER_ID
  AND B.USER_NAME LIKE '%팽%'
  ORDER BY A.BRD_GROUP DESC, A.BRD_ORDER ASC));

--좋아요
CREATE TABLE SPR_QNA_LIKE
(
    USER_ID VARCHAR2(100) NOT NULL,
    BRD_SEQ NUMBER(12) NOT NULL
);

COMMENT ON TABLE SPR_QNA_LIKE IS '좋아요 테이블';
COMMENT ON COLUMN SPR_QNA_LIKE.USER_ID IS '아이디';
COMMENT ON COLUMN SPR_QNA_LIKE.BRD_SEQ IS '게시글 번호';

ALTER TABLE SPR_QNA_LIKE
ADD CONSTRAiNT FK_SPR_QNA_LIKE_USERID FOREIGN KEY(USER_ID)
REFERENCES SPR_USER(USER_ID);

ALTER TABLE SPR_QNA_LIKE
ADD CONSTRAiNT FK_SPR_QNA_LIKE_BRDSEQ FOREIGN KEY(BRD_SEQ)
REFERENCES SPR_QNA(BRD_SEQ);

SELECT USER_ID,
       BRD_SEQ
FROM   SPR_QNA_LIKE;

INSERT INTO SPR_QNA_LIKE (
    USER_ID,
    BRD_SEQ
) VALUES (
    :V0,
    :V1
);

DELETE FROM SPR_QNA_LIKE
WHERE
        USER_ID = :V0
    AND BRD_SEQ = :V1;
    
--EXHIBITION_COMMENT 테이블
CREATE TABLE EXHIBITION_COMMENT
(   
    COMMENT_NUM NUMBER(12),
    BRD_SEQ NUMBER(12) NOT NULL,
    CONTENT VARCHAR2(500),
    USER_ID VARCHAR2(100) NOT NULL,
    REG_DATE DATE,
    PARENT_NUM NUMBER(12),
    GROUP_NUM NUMBER(12),
    ORDER_NUM NUMBER(10),
    INDENT_NUM NUMBER(10)
);

COMMENT ON TABLE EXHIBITION_COMMENT IS '게시글 댓글 테이블';
COMMENT ON COLUMN EXHIBITION_COMMENT.COMMENT_NUM IS '댓글 번호';
COMMENT ON COLUMN EXHIBITION_COMMENT.BRD_SEQ IS '게시물 번호';
COMMENT ON COLUMN EXHIBITION_COMMENT.CONTENT IS '댓글 내용';
COMMENT ON COLUMN EXHIBITION_COMMENT.USER_ID IS '댓글 작성자 ID';
COMMENT ON COLUMN EXHIBITION_COMMENT.REG_DATE IS '댓글 작성일';
COMMENT ON COLUMN EXHIBITION_COMMENT.PARENT_NUM IS '부모 댓글';
COMMENT ON COLUMN EXHIBITION_COMMENT.GROUP_NUM IS '그룹번호';
COMMENT ON COLUMN EXHIBITION_COMMENT.ORDER_NUM IS '그룹순서';
COMMENT ON COLUMN EXHIBITION_COMMENT.INDENT_NUM IS '들여쓰기';

ALTER TABLE EXHIBITION_COMMENT
ADD CONSTRAiNT FK_EXHIBITION_COMMENT_USERID FOREIGN KEY(USER_ID)
REFERENCES SPR_USER(USER_ID);

ALTER TABLE EXHIBITION_COMMENT
ADD CONSTRAiNT FK_EXHIBITION_COMMENT_BRDSEQ FOREIGN KEY(BRD_SEQ)
REFERENCES SPR_EXHIBITION(BRD_SEQ)
ON DELETE CASCADE;

--EXHIBITION_COMMENT 댓글 시퀀스
CREATE SEQUENCE SEQ_EXHIBITION_COMMENT_SEQ
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999
NOCACHE;

ALTER TABLE EXHIBITION_COMMENT
ADD CONSTRAINT EXHIBITION_COMMENT PRIMARY KEY(COMMENT_NUM);

--QNA_COMMENT
CREATE TABLE QNA_COMMENT
(   
    COMMENT_NUM NUMBER(12),
    BRD_SEQ NUMBER(12) NOT NULL,
    CONTENT VARCHAR2(500),
    USER_ID VARCHAR2(100) NOT NULL,
    REG_DATE DATE,
    PARENT_NUM NUMBER(12),
    GROUP_NUM NUMBER(12),
    ORDER_NUM NUMBER(10),
    INDENT_NUM NUMBER(10)
);

COMMENT ON TABLE QNA_COMMENT IS '게시글 댓글 테이블';
COMMENT ON COLUMN QNA_COMMENT.COMMENT_NUM IS '댓글 번호';
COMMENT ON COLUMN QNA_COMMENT.BRD_SEQ IS '게시물 번호';
COMMENT ON COLUMN QNA_COMMENT.CONTENT IS '댓글 내용';
COMMENT ON COLUMN QNA_COMMENT.USER_ID IS '댓글 작성자 ID';
COMMENT ON COLUMN QNA_COMMENT.REG_DATE IS '댓글 작성일';
COMMENT ON COLUMN QNA_COMMENT.PARENT_NUM IS '부모 댓글';
COMMENT ON COLUMN QNA_COMMENT.GROUP_NUM IS '그룹번호';
COMMENT ON COLUMN QNA_COMMENT.ORDER_NUM IS '그룹순서';
COMMENT ON COLUMN QNA_COMMENT.INDENT_NUM IS '들여쓰기';

ALTER TABLE QNA_COMMENT
ADD CONSTRAiNT FK_QNA_COMMENT_USERID FOREIGN KEY(USER_ID)
REFERENCES SPR_USER(USER_ID);

ALTER TABLE QNA_COMMENT
ADD CONSTRAiNT FK_QNA_COMMENT_BRDSEQ FOREIGN KEY(BRD_SEQ)
REFERENCES SPR_QNA(BRD_SEQ);

--QNA_COMMENT 댓글 시퀀스
CREATE SEQUENCE SEQ_QNA_COMMENT_SEQ
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999
NOCACHE;

ALTER TABLE QNA_COMMENT
ADD CONSTRAINT QNA_COMMENT PRIMARY KEY(COMMENT_NUM);

SELECT  BRD_SEQ,
        NVL(USER_ID, '') USER_ID,
        NVL(CONTENT, '') CONTENT,
        NVL(COMMENT_NUM, 0) COMMENT_NUM,
        NVL(TO_CHAR(REG_DATE, 'YYYY.MM.DD HH24:MI:SS'), '') REG_DATE,
        NVL(PARENT_NUM, 0) PARENT_NUM,
        NVL(GROUP_NUM, 0) GROUP_NUM,
        NVL(ORDER_NUM, 0) ORDER_NUM,
        NVL(INDENT_NUM, 0) INDENT_NUM
  FROM  QNA_COMMENT
 WHERE  BRD_SEQ = #{BRDSEQ}
 ORDER BY REGDATE ASC;
 
 INSERT INTO QNA_COMMENT (
    COMMENT_NUM,
    BRD_SEQ,
    CONTENT,
    USER_ID,
    REG_DATE,
    PARENT_NUM,
    GROUP_NUM,
    ORDER_NUM,
    INDENT_NUM
) VALUES (
    #{commentNum},
    #{brdSeq},
    #{content},
    #{userId},
    SYSDATE,
    #{parentNum},
    #{groupNum},
    #{orderNum},
    #{indent_num}
);

SELECT  BRD_SEQ,
		        NVL(USER_ID, '') USER_ID,
		        NVL(CONTENT, '') CONTENT,
		        NVL(COMMENT_NUM, 0) COMMENT_NUM,
		        NVL(TO_CHAR(REG_DATE, 'YYYY.MM.DD HH24:MI:SS'), '') REG_DATE,
		        NVL(PARENT_NUM, 0) PARENT_NUM,
		        NVL(GROUP_NUM, 0) GROUP_NUM,
		        NVL(ORDER_NUM, 0) ORDER_NUM,
		        NVL(INDENT_NUM, 0) INDENT_NUM

		  FROM  EXHIBITION_COMMENT

		 WHERE  BRD_SEQ = '55'
		   AND	COMMENT_NUM = '71'